apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-echo-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: simple-echo
      labels:
        app: simple-echo-app
        tier: api
    spec:
      containers:
      - name: simple-echo-pod-container
        image: liu71101/simple-echo
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: simple-echo-app
      tier: api