apiVersion: v1
kind: Service
metadata:
  name: hello-nodeport-service
spec:
  sessionAffinity: ClientIP
  type: NodePort
  selector:
    tier: frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
    protocol: TCP