apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        type: frontend
    spec:
      containers:
      - name: nginx-pod-container
        image: nginx:1.15-alpine
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      type: frontend