apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    tier: frontend
spec:
  containers:
  - name: hello-pod-container
    image: paulbouwer/hello-kubernetes:1.5
    ports:
    - containerPort: 8080